-- Data to populate the database

USE Happy_Trails

CREATE TABLE tblPHONE_TYPE
    (PhoneTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     PhoneTypeName VARCHAR(50) NOT NULL,
	 PhoneTypeDescr VARCHAR(100) NULL)

CREATE TABLE tblCONTACT_TYPE
    (ContactTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     ContactTypeName VARCHAR(50) NOT NULL,
	 ContactTypeDescr VARCHAR(250) NULL)

CREATE TABLE tblASSOCIATION_TYPE
    (AssociationTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     AssociationTypeName VARCHAR(50) NOT NULL,
	 AssociationTypeDescr VARCHAR(500) NULL)

CREATE TABLE tblATTRACTION_TYPE
    (AttractionTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     AttractionTypeName VARCHAR(50) NOT NULL,
	 AttractionTypeDescr VARCHAR(500) NULL)

CREATE TABLE tblCOMMENT
	(CommentID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     CommentBody VARCHAR(4000) NOT NULL,
	 CommentDate DATE NOT NULL)

CREATE TABLE tblRATING
    (RatingID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     RatingNumber INT NOT NULL,
	 RatingDescr VARCHAR(500) NULL)

CREATE TABLE tblEXPERIENCE
    (ExperienceID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     ExperienceName VARCHAR(50) NOT NULL,
	 ExperienceDescr VARCHAR(500) NULL)

CREATE TABLE tblLEVEL
    (LevelID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     LevelName VARCHAR(50) NOT NULL,
	 LevelDescr VARCHAR(500) NULL)

CREATE TABLE tblREGION
    (RegionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     RegionName VARCHAR(50) NOT NULL,
	 RegionDescr VARCHAR(500) NULL)

CREATE TABLE tblPHONE
	(PhoneID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	 AreaCode VARCHAR(3) NOT NULL,
	 PhoneNumber VARCHAR(7) NOT NULL,
	 PhoneTypeID INT FOREIGN KEY REFERENCES tblPHONE_TYPE(PhoneTypeID) NOT NULL)

CREATE TABLE tblCONTACT
    (ContactID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     ContactTypeID INT FOREIGN KEY REFERENCES tblCONTACT_TYPE(ContactTypeID) NOT NULL,
	 ContactFName VARCHAR(50) NOT NULL,
	 ContactLName VARCHAR(50) NOT NULL,
	 ContactEmail VARCHAR(320) NOT NULL)

CREATE TABLE tblASSOCIATION
    (AssociationID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     AssociationName VARCHAR(50) NOT NULL,
	 AssociationTypeID INT FOREIGN KEY REFERENCES tblASSOCIATION_TYPE(AssociationTypeID) NOT NULL,
	 AssociationState VARCHAR(25) NULL,
	 AssociationCity VARCHAR(50) NULL,
	 AssociationZipCode VARCHAR(5) NULL)

CREATE TABLE tblATTRACTION
    (AttractionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     AttractionTypeID INT FOREIGN KEY REFERENCES tblATTRACTION_TYPE(AttractionTypeID) NOT NULL,
	 AttractionName VARCHAR(50) NOT NULL,
	 AttractionDescr VARCHAR(500) NULL)

CREATE TABLE tblHIKER_TYPE
    (HikerTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     HikerTypeName VARCHAR(50) NOT NULL,
	 ExperienceID INT FOREIGN KEY REFERENCES tblEXPERIENCE(ExperienceID) NOT NULL,
	 StartDate DATE NULL)

CREATE TABLE tblTRAIL
    (TrailID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     TrailName VARCHAR(100) NOT NULL,
	 RegionID INT FOREIGN KEY REFERENCES tblREGION(RegionID) NOT NULL,
	 LevelID INT FOREIGN KEY REFERENCES tblLEVEL(LevelID) NOT NULL)

CREATE TABLE tblCONTACT_PHONE
    (ContactID INT FOREIGN KEY REFERENCES tblCONTACT(ContactID) NOT NULL,
     PhoneID INT FOREIGN KEY REFERENCES tblPHONE(PhoneID) NOT NULL,
	 PRIMARY KEY(ContactID, PhoneID))

CREATE TABLE tblASSOCIATION_CONTACT
    (AssociationID INT FOREIGN KEY REFERENCES tblASSOCIATION(AssociationID) NOT NULL,
     ContactID INT FOREIGN KEY REFERENCES tblCONTACT(ContactID) NOT NULL,
	 PRIMARY KEY(AssociationID, ContactID))

CREATE TABLE tblASSOCIATION_TRAIL
    (AssociationID INT FOREIGN KEY REFERENCES tblASSOCIATION(AssociationID) NOT NULL,
     TrailID INT FOREIGN KEY REFERENCES tblTRAIL(TrailID) NOT NULL,
	 PRIMARY KEY(AssociationID, TrailID))

CREATE TABLE tblDESCRIPTION
	(DescriptionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	 TrailLength INT NOT NULL,
	 TrailElevation INT NOT NULL,
	 TrailAddress VARCHAR(200) NOT NULL,
	 TrailCity VARCHAR(50) NOT NULL,
	 TrailState VARCHAR(25) NOT NULL,
	 TrailZipCode VARCHAR(5) NOT NULL,
	 TrailID INT FOREIGN KEY REFERENCES tblTRAIL(TrailID) NOT NULL)

CREATE TABLE tblDESCRIPTION_ATTRACTION
    (DescriptionID INT FOREIGN KEY REFERENCES tblDESCRIPTION(DescriptionID) NOT NULL,
     AttractionID INT FOREIGN KEY REFERENCES tblATTRACTION(AttractionID) NOT NULL,
	 PRIMARY KEY(DescriptionID, AttractionID))

CREATE TABLE tblHIKER
    (HikerID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     HikerTypeID INT FOREIGN KEY REFERENCES tblHIKER_TYPE(HikerTypeID) NULL,
	 HikerFName VARCHAR(50) NOT NULL,
	 HikerLName VARCHAR(50) NOT NULL,
	 HikerAddress VARCHAR(200) NULL,
	 HikerCity VARCHAR(50) NULL,
	 HikerState VARCHAR(25) NULL,
	 HikerPhoneNumber VARCHAR(10) NULL,
	 HikerDateOfBirth DATE NULL)

CREATE TABLE tblTRAIL_HIKER
	(TrailHikerID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	 TrailID INT FOREIGN KEY REFERENCES tblTRAIL(TrailID) NOT NULL,
	 HikerID INT FOREIGN KEY REFERENCES tblHIKER(HikerID) NOT NULL,
	 Date DATE NOT NULL)

CREATE TABLE tblREVIEW
    (ReviewID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     CommentID INT FOREIGN KEY REFERENCES tblCOMMENT(CommentID) NOT NULL,
	 RatingID INT FOREIGN KEY REFERENCES tblRATING(RatingID) NOT NULL,
	 TrailHikerID INT FOREIGN KEY REFERENCES tblTRAIL_HIKER(TrailHikerID) NOT NULL)
